### ISSUE TITLE
Travis build automation (osx)

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#100]
Part of #94 .
Implement basic travis infrastructure for osx build.

**Comment by brenhow** [comment]
I am trying to use ComicTagger on MacOS Sierra 10.12.6 and all queries are failing, either Auto-Tag or Search Online is failing, even when I search for something as simple as Spider-Man. Is this a known issue?

**Comment by eduo** [comment]
I believe comicvine changed its search engine, which affected how it returns results. My manual searches were coming up empty a couple of weeks ago and now searches throw hundreds of results.

This matches with behaviour seen in the developer forums: https://comicvine.gamespot.com/forums/api-developers-2334/searches-not-working-correctly-from-comicvine-scra-1922307/#15

Today, "Wildcats vs Aliens" throws over 800 results, since it matches "wildcats", "vs", "aliens" and any combination thereof. 

I'm not sure if it's possible to trim down the results or do a fuzzy search to not have to query each of them. It's becoming might easy to hit Comicvine daily limits now.

As it is, the search went from one unworkable extreme to the other. Hopefully it'll find its middle soon.

**Comment by davide-romanini** [comment]
Implemented initial github automatic release of the generated application.
