### ISSUE TITLE
searching/tagging for titles with hyphens not working

### ISSUE THREAD

**Issue by jdinda70** [davide-romanini/comictagger#112]
Within ComicTagger, I am trying search for titles with hyphens in them (for example, "Sub-Mariner" or "Spider-Man".

When I do, I always get a "no matches found" search result.  Of course, the same thing happens with the Auto-Identify and Auto-Tag options (no matches for titles with hyphenated words in the title)

However, when I search for either of the components of the hyphenated words ("Sub", "Mariner", "Spider", or "Man") I do get the expected results (however, given the examples above the lists are big, and since the Autotag doesn't work with the complete word, it cannot be used to batch tag files with series titles that include a hyphenated word.

I don't know when this functionality changed.  I know that it used to work in the past (I tagged a bunch of Spider-Man comics a few years ago without issue).

I am running the latest version (Developer code - 1.1.20 SNAPSHOT, downloaded today)

**Comment by jdinda70** [comment]
Update: I got the 108-py3qt5 version working today, and this issue does not seem to be present.  Thank you!

**Comment by trumblejoe** [comment]
I'm going to follow this up with some more helpful information. Comic Vine Scraper had some of the same issues with querying the Comic Vine API. You can see some of their fixes here, https://github.com/cbanack/comic-vine-scraper/commits/master

**Comment by casperOne** [comment]
@jdinda70 As someone not versed in python, can you go over how you got this to work?  Was it on Windows or on another platform?

**Comment by jdinda70** [comment]
@casperOne I just installed the feature/108-py3qt5 build on Windows.  Installed the pre-reqs 1st. (Python w/ PIP, modules listed via PIP, unrar DLL and Winrar).  I found it much easier to get working than previous builds.

While searches with hyphenated words are much better, there are still search issues (the biggest being that any searches of titles with an ampersand - "&" - in them don't return good results).

**Comment by thomassrob** [comment]
I started playing around with this. I've got a modified version of the develop branch running on a Mac. Removing the line that removes dashes from the search string seems to fix the dash issue (solution stolen from the Comic Vine Scraper list above).

I'm mucking with the rest in a fork. I assume there's interest in the fixes back here if I sort them out?

**Comment by jdinda70** [comment]
definitely, but I am currently running the feature/108-py3qt5 build and some of the issues seem to already be resolved in that one (although I have seen a few other issues, including searches with ampersands in them as I pointed out above).  I don't know if you can fork off the feature/108-py3qt5 build.  I don't really know how the commits will work if there are multiple changes to the same functionality.

**Comment by thomassrob** [comment]
The fixes I've made so far are tiny enough that manually reapplying them (as a worse case scenario) isn't an issue. I'll work on the rest and then sort out how to submit them back. 

I'm new to Git (I'm more used to Perforce& CVS, which makes me sound super old). I forked this project as a chance to learn it and dust off my ancient Python skills, as well as because I use it regularly.

**Comment by casperOne** [comment]
@jdinda70 How did you get the unrar libraries installed?

I have the latest version of WinRaR installed, but it won't accept CBR files.

I tried running beville/comictagger from code, but that didn't work either (there's indication that there's UI support to configure UnRar).

I suspect once I have the unrar library installed, I can process cbr files.

**Comment by jdinda70** [comment]
You need to install the Unrar DLL (there is a link in the settings to the page where you can download it from).

After you install, the path for 64-bit windows is: C:\Program Files (x86)\UnrarDLL\x64\UnRAR64.dll

**Comment by eduo** [comment]
There's a change that seems to fix this, addressing a specific rule currently in the source: https://github.com/thomassrob/comictagger/commit/d374cf28dc5ef3f78d2ae02638ec42f327df7200

This essentially removes the current rule that removes the dash and replaces it with a space. The rule should either search with the dash or remove the dash and join the words together (either of these work in the search API for Comicvine, but the current behaviour fails).

A more complex problem happens for names that have a colon (":") since those seem to be required by comicvine today, but they can't come from the file name.

A new RC4 would be ideal with this change, replacing the current RC3: https://github.com/davide-romanini/comictagger/releases
