### ISSUE TITLE
URLOpen returns a TLSV1_ALERT_PROTOCOL_VERSION

### ISSUE THREAD

**Issue by omgthegreenranger** [davide-romanini/comictagger#137]
Some time in the past couple of weeks, ComicVine has stopped being reachable on ComicTagger. I don't know why - testing my key tells me it isn't valid, and trying to search suddenly stopped with the error:

<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1076)>

This is not the case with Calibre, and trying to access the API via the browser works fine.

I've seen a bunch of people saying that rebooting fixed it, which didn't work. Could it have to do with Arch updating the OpenSSL repository to v 1.1.1 this month?

**Comment by FelixLehmannBLN** [comment]
I get the same error:
"Could not connect to comic vine to search for series" :(

**Comment by apastuszak** [comment]
Glad it's not just me.

**Comment by bpepple** [comment]
This should fix it: https://github.com/davide-romanini/comictagger/pull/135

**Comment by eduo** [comment]
I asked in #135. Perhaps someone here could answer:

I'm not able to compile the latest version with the fix in MacOS Mojave, nor can I manage to run the source code manually from the terminal. All dependencies are theoretically met.

Does anyone have an update list of instructions for compiling for MacOS or an updated binary with this fix?

I would much prefer the former, since each time a Binary is shared (which I'm ultimately thankful for) the poster mentions how hard it was to make it compile, but doesn't share how he/she did it.

**Comment by davide-romanini** [comment]
I release a 1.1.32-rc1 version with the changes made on #135. 
@eduo I compiled and tested the macOS version on Mojave. Hope this helps.

**Comment by angryjonny** [comment]
> I release a 1.1.32-rc1 version with the changes made on #135.
> @eduo I compiled and tested the macOS version on Mojave. Hope this helps.

Works for me. Thank you very much!
